version: "3.2"

services:
  php:
    container_name: ${COMPOSE_PROJECT_NAME}_php
    image: vavyskov/php-ssh:${PHP_VERSION}-apache-stretch
    hostname: ${COMPOSE_PROJECT_NAME}.local
    depends_on:
      - mariadb
    ports:
      - "80:80"
      - "2201:22"
    volumes:
      - html:/var/www/html
  mariadb:
    container_name: ${COMPOSE_PROJECT_NAME}_mariadb
    image: mariadb:${MARIADB_VERSION:-latest}
    environment:
      MYSQL_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MARIADB_DATABASE}"
      MYSQL_USER: "${MARIADB_USERNAME}"
      MYSQL_PASSWORD: "${MARIADB_PASSWORD}"
    ports:
      - "3306:3306"
    volumes:
      - mariadb:/var/lib/mysql
  adminer:
    container_name: ${COMPOSE_PROJECT_NAME}_adminer
    image: adminer:latest
    ports:
      - "8080:8080"
  mailcatcher:
    container_name: ${COMPOSE_PROJECT_NAME}_mailcatcher
    image: vavyskov/mailcatcher
    ports:
      - "1080:80"
      - "1025:25"
volumes:
  html:
  mariadb: